### ISSUE TITLE
Switch from namespace to data attributes

### ISSUE THREAD

**Issue by fabiofabbrucci** [mnot/hinclude#13]
Hi @mnot ,
what do you think about switch from this
```html
<hx:include src="http://www.google.it" id="google"></hx>
```
to this
```html
<div data-src="http://www.google.it" id="google">
```
?

I dont like so much to add a new namespace, so I would prefer to use a TAG that is already available in DTD.
Can you see any problems in this?

**Comment by mnot** [comment]
Web Components is coming along nicely, but at this point it doesn't make sense to load polymer if you're just using hinclude. When Web Components is more widely implemented, can revisit.

**Comment by mnot** [comment]
See #46.
