### ISSUE TITLE
Add X-Requested-With header

### ISSUE THREAD

**Issue by tkleinhakisa** [mnot/hinclude#16]
Hi,

I think it should be nice to have hinclude send and "X-Requested-With" header with the value "XMLHttpRequest"

Most js framework send this header with ajax requests and the server side framework i know (including symfony2 which has support for hinclude) use this header to help detect ajax requests

Thanks
Tom

**Comment by peter-gribanov** [comment]
+1 I do not think it's right to give a different content (different layout) for a single URL. But we need to be able to distinguish AJAX requests and full requests.
For example, i do not want to content loaded via AJAX was available in full request. For example, without this restriction, you can freely embed content on other sites. Of course, this restriction is easy to get around, but that is no reason not to use it.

**Comment by bluesmoon** [comment]
@peter-gribanov it causes performance problems.  Do not do it.  Use the standard `Accept` header instead.  See https://www.soasta.com/blog/options-web-performance-with-single-page-applications/ for details.

**Comment by peter-gribanov** [comment]
@bluesmoon currently headlines `X-Requested-With` or `Accept` are not forcibly sent. When you send the AJAX request, `Accept` header is set to `*/*`. Do you really think it is right to identify the AJAX request?

**Comment by bluesmoon** [comment]
`Accept` is the right header.  You should not be "identifying AJAX" (ie, transport method), you should be "identifying required content".

**Comment by peter-gribanov** [comment]
@bluesmoon no. In this case, the content will be same in both cases, but the call context differs.
Identify call context can only be by headers `X-Requested-With` and `Referer`. Header `Accept` indicates that we expect to receive and in both cases it will be a `text/html` because the library can load only HTML code.

**Comment by bluesmoon** [comment]
If the content is the same then why does it matter what the requesting context is?  The whole point of using HTTP is that the requesting context is irrelevant.

**Comment by peter-gribanov** [comment]
@bluesmoon yes, that's right. But i'm interested in the ability to block access to content that is not supposed to show in full request.

**Comment by bluesmoon** [comment]
Then you should use a query string parameter or different URL to distinguish.  Your client & server may understand custom HTTP headers, but intermediate proxies will not, which means they might respond with cached copies based on the URL and some of the basic content headers.  I've seen intermediate proxies also ignore Cache-control headers (and a smaller number even ignore query strings), so a different URL is really the only way to handle this particular case.
