### ISSUE TITLE
Hinclude on event (like click)

### ISSUE THREAD

**Issue by L0rD59** [mnot/hinclude#30]
Hi all,

i want use hinclude on a event (click on button)

but i cant "prepare" a hx:include, add a src on event and refresh it

if i do : 

```
<hx:include></hx:include>
```

i obtain a error "url is null"

so i do : 

```
$('#container').html('<hx:include src="/hincludePage"></hx:include>');
hinclude.run();
```

do u have a better solution ?

thx for your time

**Comment by Arkemlar** [comment]
I had to modify hinclude for this to work. The original code part is:
```js
run: function () {
//...
this.includes = document.getElementsByTagName("hx:include");
```
My first approach was:
```js
run: function (id) {
//...
if(id){
        this.includes = document.querySelectorAll("hx\\:include#"+id);
      } else {
        this.includes = document.querySelectorAll("hx\\:include:not(.hinclude-deferred)");  // Used class
      }
```
But then I decided to get rid of `hx:include` tags in custom includes but keep `hx:include` compatibility for  `render_hinclude` function used in symfony framework which I use:
```js
run: function (id) {
//...
if(id){
        this.includes = document.querySelectorAll("hx-include-deferred#"+id); // Used custom tag
      } else {
	this.includes = document.getElementsByTagName("hx:include");
}
```
Now to call load manually I used:
```html
<script>
	function hinclude_run(id){
		hinclude.run('hinclude'+id);
	}
</script>
<button type="button" onclick="hinclude_run({{ your_id }})">Загрузить</button>
<hx:include src="..." class="hinclude-deferred" id="hinclude{{ id }}"></hx-include-deferred>
<!-- for custom tag: -->
<hx-include-deferred src="..." id="hinclude{{ id }}"></hx-include-deferred>
```
P.S.: I'm back-end man so my approach might look bad for front-end skilled guys, so if I did something too wrong - feel free to point on my fault :)
