### ISSUE TITLE
Does not update the contents in Internet Explorer

### ISSUE THREAD

**Issue by jaimevalasek** [mnot/hinclude#39]
Hello, I'm using hinclude with Symfony2 and have on my site a login AJAX, just after the authentication is successful I update the contents of blocks loaded by hinclude, this works very well on all major browsers, but in internet explorer does not work.

Anyone ever had this problem or know how to solve?

The website is: https://www.aprovaconcursos.com.br/questoes-de-concurso/questoes

**Comment by mnot** [comment]
Did you include xmlns:hx="http://purl.org/NET/hinclude" on the HTML element?

**Comment by mnot** [comment]
Closing do to lack of response.
