### ISSUE TITLE
Async add table rows

### ISSUE THREAD

**Issue by tanguybernard** [mnot/hinclude#43]
I want to include rows in a async fashion to speed up page loading and for better caching of the view fragments.

Therefore I use hinclude.js to load the fragment asynchronously. The fragment just contains a table row (e.g.):

tr
        td 29 /td
        td 60% /td
        td Foo, Bla /td
/tr

Problem is that this is not added as html at the position, the browser does interpret it before positioning it. This leads to the result that all tr and td are stripped away.
Any solution to use hinclude to just load some table rows?

Thanks in advance.

source : http://w3javascript.com/question/async-add-table-rows/

**Comment by mnot** [comment]
I think you're probably looking for something a lot different than hinclude; what you're seeing is caused by how the browser layout engine works.
