### ISSUE TITLE
Async data display

### ISSUE THREAD

**Issue by surgun9** [mnot/hinclude#47]
on a symfony2.6 page I have several blocks that are rendered by twig render_hinclude.
The response content doesn't updated asynchronously but waits while all hinclude requests will finish and then updates all blocks with corresponding content.

Is it possible to make it to display content immediately as request is finished.
thanks

**Comment by mnot** [comment]
See "rendering mode" in the [docs](https://mnot.github.io/hinclude/).

**Comment by surgun9** [comment]
thank you very much =))
