### ISSUE TITLE
Controller attributes cannot contain non-scalar\/non-null values

### ISSUE THREAD

**Issue by tanguybernard** [mnot/hinclude#58]
I would like to provide my controller object like this with hinclude.js :

`{{ render_hinclude(controller("AppBundle:Default:Test"), { 'my_object': object }) }}`

Unfortunately I got this error:

> An exception has been thrown during the rendering of a template (\"Controller attributes cannot contain non-scalar/non-null values (value for key \"object\" is not a scalar or null).\")

Can you help me ?

Thanks in advance !

**Comment by mnot** [comment]
hinclude doesn't have a `render_hinclude` method or a `controller` object - wrong repo?

**Comment by tanguybernard** [comment]
In documentation( http://mnot.github.io/hinclude/) I saw :

```
Or in symfony :
     {{ render_hinclude(url('here_route'), {id: 'my-id', attributes: {"data-with-credentials": "true"} }) }}
```

I forget to precise, Its symfony2 project.
