### ISSUE TITLE
Bower archive is outdated

### ISSUE THREAD

**Issue by adrien-mallet** [mnot/hinclude#59]
Hi,
I am not really sure whether the problem is on mnot/hinclude repository but when bower downloads https://github.com/mnot/hinclude/archive/v1.0.1.tar.gz
the hinclude.js file seems to be outdated (trigger_event, set_class are missing, ...)
I have tried to clean my cache but nothing has changed.

Thank you for your work.

**Comment by skrosoft** [comment]
+1

**Comment by mnot** [comment]
Sorry for the wait.
