### ISSUE TITLE
can you make a new stable release

### ISSUE THREAD

**Issue by ickbinhier** [mnot/hinclude#63]
can you make a new stable release

**Comment by ickbinhier** [comment]
@mnot

**Comment by guill3m** [comment]
@mnot I see version 1.1.0 is tagged in Github but not released in npm, making it harder to update to this newer version.

For now we are using `mnot/hinclude#1.1.0` and it works fine, ideally we would just have to to rely on the semver “compatible with version” like we were doing before updating and with all our other dependencies.

Thank you.

**Comment by ickbinhier** [comment]
after version 1.1.0 come a pull request with --evaljs='true'--
i need this. this is my problem.

**Comment by mnot** [comment]
Sorry about that; just did `npm publish`.

**Comment by guill3m** [comment]
Thank you @mnot
