### ISSUE TITLE
The homepage URL in the repo description is wrong

### ISSUE THREAD

**Issue by stof** [mnot/hinclude#76]
It should use https://mnot.github.io/hinclude/, not https://mnot.github.com/hinclude/

**Comment by stof** [comment]
@mnot you fixed a link in the readme, but the issue reported with the repo description is still not fixed:
![image](https://user-images.githubusercontent.com/439401/232412371-4f8733d9-ebe6-4c1d-85e6-b06b0a4df6be.png)

**Comment by mnot** [comment]
Aha! Thanks!
